#define DYN_SYMBOL_DEFAULT(name) DYN_SYMBOL(name, name)
#define DYN_SYMBOL_DATA_DEFAULT(name) DYN_SYMBOL_DATA(name, name)

DYN_SYMBOL_DATA(_ctype_, __ctype_)
//        {"_tolower_tab_",               (uintptr_t) &_tolower_tab_},
//        {"_toupper_tab_",               (uintptr_t) &_toupper_tab_},
DYN_SYMBOL_DATA_DEFAULT(__cxa_atexit)
DYN_SYMBOL_DATA_DEFAULT(__cxa_finalize)
DYN_SYMBOL_DATA_DEFAULT(__errno)
//        {"__gnu_Unwind_Find_exidx",     (uintptr_t) &__gnu_Unwind_Find_exidx},
DYN_SYMBOL_DEFAULT(__isinff)
DYN_SYMBOL_DATA(__sF, __sF_fake)
DYN_SYMBOL_DATA_DEFAULT(__stack_chk_fail)
DYN_SYMBOL_DATA(__stack_chk_guard, __stack_chk_guard_fake)
DYN_SYMBOL_DEFAULT(AAssetManager_fromJava)
DYN_SYMBOL_DEFAULT(AAssetManager_open)
DYN_SYMBOL_DEFAULT(AAsset_close)
DYN_SYMBOL_DEFAULT(AAsset_getRemainingLength)
DYN_SYMBOL_DEFAULT(AAsset_read)
DYN_SYMBOL_DEFAULT(AAsset_seek)
DYN_SYMBOL_DEFAULT(abort)
DYN_SYMBOL_DEFAULT(accept)
DYN_SYMBOL_DEFAULT(AConfiguration_delete)
DYN_SYMBOL_DEFAULT(AConfiguration_fromAssetManager)
DYN_SYMBOL_DEFAULT(AConfiguration_getLanguage)
DYN_SYMBOL_DEFAULT(AConfiguration_new)
DYN_SYMBOL_DEFAULT(acos)
DYN_SYMBOL_DEFAULT(acosf)
DYN_SYMBOL_DEFAULT(ANativeWindow_fromSurface)
DYN_SYMBOL_DEFAULT(ANativeWindow_getHeight)
DYN_SYMBOL_DEFAULT(ANativeWindow_getWidth)
DYN_SYMBOL_DEFAULT(ANativeWindow_release)
DYN_SYMBOL_DEFAULT(ANativeWindow_setBuffersGeometry)
DYN_SYMBOL_DEFAULT(asin)
DYN_SYMBOL_DEFAULT(asinf)
DYN_SYMBOL_DEFAULT(atan)
DYN_SYMBOL_DEFAULT(atan2)
DYN_SYMBOL_DEFAULT(atan2f)
DYN_SYMBOL_DEFAULT(atanf)
DYN_SYMBOL_DEFAULT(atof)
DYN_SYMBOL_DEFAULT(atoi)
DYN_SYMBOL_DEFAULT(atol)
DYN_SYMBOL_DEFAULT(bind)
DYN_SYMBOL_DEFAULT(btowc)
DYN_SYMBOL_DEFAULT(calloc)
DYN_SYMBOL_DEFAULT(ceil)
DYN_SYMBOL_DEFAULT(ceilf)
DYN_SYMBOL_DEFAULT(clock)
DYN_SYMBOL_DEFAULT(clock_gettime)
DYN_SYMBOL_DEFAULT(close)
DYN_SYMBOL_DEFAULT(connect)
DYN_SYMBOL_DEFAULT(cos)
DYN_SYMBOL_DEFAULT(cosf)
DYN_SYMBOL_DEFAULT(cosh)
DYN_SYMBOL_DEFAULT(difftime)
DYN_SYMBOL_DEFAULT(eglBindAPI)
DYN_SYMBOL_DEFAULT(eglChooseConfig)
DYN_SYMBOL_DEFAULT(eglCreateContext)
DYN_SYMBOL_DEFAULT(eglCreateWindowSurface)
DYN_SYMBOL_DEFAULT(eglGetConfigAttrib)
DYN_SYMBOL(eglGetDisplay, ret0)
DYN_SYMBOL_DEFAULT(eglGetProcAddress)
DYN_SYMBOL_DEFAULT(eglInitialize)
DYN_SYMBOL_DEFAULT(eglMakeCurrent)
DYN_SYMBOL_DEFAULT(eglSwapBuffers)
DYN_SYMBOL_DEFAULT(eglSwapInterval)
DYN_SYMBOL_DEFAULT(exit)
DYN_SYMBOL_DEFAULT(exp)
DYN_SYMBOL_DEFAULT(fclose)
DYN_SYMBOL_DEFAULT(fcntl)
DYN_SYMBOL_DEFAULT(fdopen)
DYN_SYMBOL_DEFAULT(fflush)
DYN_SYMBOL_DEFAULT(fgets)
DYN_SYMBOL_DEFAULT(floor)
DYN_SYMBOL_DEFAULT(floorf)
DYN_SYMBOL_DEFAULT(fmod)
DYN_SYMBOL_DEFAULT(fmodf)
DYN_SYMBOL_DEFAULT(fopen)
DYN_SYMBOL_DEFAULT(fprintf)
DYN_SYMBOL_DEFAULT(fputc)
DYN_SYMBOL_DEFAULT(fputs)
DYN_SYMBOL_DEFAULT(fread)
DYN_SYMBOL_DEFAULT(free)
DYN_SYMBOL_DEFAULT(freeaddrinfo)
DYN_SYMBOL_DEFAULT(freopen)
DYN_SYMBOL_DEFAULT(frexp)
DYN_SYMBOL_DEFAULT(fscanf)
DYN_SYMBOL_DEFAULT(fseek)
DYN_SYMBOL_DEFAULT(fstat)
DYN_SYMBOL_DEFAULT(ftell)
DYN_SYMBOL_DEFAULT(fwrite)
DYN_SYMBOL_DEFAULT(getaddrinfo)
DYN_SYMBOL_DEFAULT(getc)
DYN_SYMBOL_DEFAULT(getenv) // TODO no env
DYN_SYMBOL_DEFAULT(gethostbyname)
DYN_SYMBOL_DEFAULT(gethostname)
DYN_SYMBOL_DEFAULT(getpeername)
DYN_SYMBOL_DEFAULT(getsockname)
DYN_SYMBOL_DEFAULT(gettid)
DYN_SYMBOL_DEFAULT(gettimeofday)
DYN_SYMBOL_DEFAULT(getwc)
DYN_SYMBOL_DEFAULT(glActiveTexture)
DYN_SYMBOL_DEFAULT(glBindTexture)
DYN_SYMBOL_DEFAULT(glBlendFunc)
DYN_SYMBOL_DEFAULT(glClear)
DYN_SYMBOL_DEFAULT(glClearColor)
DYN_SYMBOL_DEFAULT(glClearDepthf)
DYN_SYMBOL_DEFAULT(glClearStencil)
DYN_SYMBOL_DEFAULT(glColorMask)
DYN_SYMBOL(glCompressedTexImage2D, glCompressedTexImage2DHook)
DYN_SYMBOL_DEFAULT(glCopyTexSubImage2D)
DYN_SYMBOL_DEFAULT(glCullFace)
DYN_SYMBOL_DEFAULT(glDeleteBuffers)
DYN_SYMBOL_DEFAULT(glDeleteTextures)
DYN_SYMBOL_DEFAULT(glDepthFunc)
DYN_SYMBOL_DEFAULT(glDepthMask)
DYN_SYMBOL_DEFAULT(glDisable)
DYN_SYMBOL_DEFAULT(glDrawArrays)
DYN_SYMBOL_DEFAULT(glEnable)
DYN_SYMBOL_DEFAULT(glEnableClientState)
DYN_SYMBOL_DEFAULT(glFrontFace)
DYN_SYMBOL_DEFAULT(glGenBuffers)
DYN_SYMBOL_DEFAULT(glGenTextures)
DYN_SYMBOL_DEFAULT(glGetError)
DYN_SYMBOL_DEFAULT(glGetIntegerv)
DYN_SYMBOL_DEFAULT(glGetString)
DYN_SYMBOL(glPixelStorei, ret0)
DYN_SYMBOL_DEFAULT(glScissor)
DYN_SYMBOL_DEFAULT(glStencilFunc)
DYN_SYMBOL_DEFAULT(glStencilMask)
DYN_SYMBOL_DEFAULT(glStencilOp)
DYN_SYMBOL(glTexImage2D, glTexImage2DHook)
DYN_SYMBOL_DEFAULT(glTexParameterf)
DYN_SYMBOL_DEFAULT(glTexParameteri)
DYN_SYMBOL_DEFAULT(glViewport)
DYN_SYMBOL_DEFAULT(gmtime)
DYN_SYMBOL_DEFAULT(ioctl)
DYN_SYMBOL_DEFAULT(islower)
DYN_SYMBOL_DEFAULT(isupper)
DYN_SYMBOL_DEFAULT(iswctype)
DYN_SYMBOL_DEFAULT(ldexp)
DYN_SYMBOL_DEFAULT(listen)
DYN_SYMBOL_DEFAULT(localtime)
DYN_SYMBOL_DEFAULT(log)
DYN_SYMBOL_DEFAULT(log10)
DYN_SYMBOL_DEFAULT(logf)
DYN_SYMBOL_DEFAULT(longjmp)
DYN_SYMBOL_DEFAULT(lrand48)
DYN_SYMBOL_DEFAULT(lseek)
DYN_SYMBOL_DEFAULT(malloc)
DYN_SYMBOL_DEFAULT(mbrtowc)
DYN_SYMBOL(memchr, sceClibMemchr)
DYN_SYMBOL(memcmp, sceClibMemcmp)
DYN_SYMBOL(memcpy, sceClibMemcpy)
DYN_SYMBOL(memmove, sceClibMemmove)
DYN_SYMBOL(memset, sceClibMemset)
DYN_SYMBOL_DEFAULT(mkdir)
DYN_SYMBOL_DEFAULT(mktime)
DYN_SYMBOL_DEFAULT(modf)
DYN_SYMBOL_DEFAULT(opendir)
DYN_SYMBOL_DEFAULT(poll)
DYN_SYMBOL_DEFAULT(pow)
DYN_SYMBOL_DEFAULT(powf)
DYN_SYMBOL_DEFAULT(printf)
DYN_SYMBOL(pthread_attr_destroy, ret0)
DYN_SYMBOL_DEFAULT(pthread_attr_getschedparam) // todo 感觉都应该 ret0
DYN_SYMBOL(pthread_attr_init, ret0)
DYN_SYMBOL(pthread_attr_setdetachstate, ret0)
DYN_SYMBOL_DEFAULT(pthread_attr_setschedparam)
DYN_SYMBOL_DEFAULT(pthread_attr_setschedpolicy)
DYN_SYMBOL_DEFAULT(pthread_attr_setstacksize)
DYN_SYMBOL_DEFAULT(pthread_condattr_destroy)
DYN_SYMBOL_DEFAULT(pthread_condattr_init)
DYN_SYMBOL(pthread_cond_broadcast, pthread_cond_broadcast_fake)
DYN_SYMBOL(pthread_cond_destroy, pthread_cond_destroy_fake)
DYN_SYMBOL(pthread_cond_init, pthread_cond_init_fake)
DYN_SYMBOL(pthread_cond_signal, pthread_cond_signal_fake)
DYN_SYMBOL(pthread_cond_timedwait, pthread_cond_timedwait_fake)
DYN_SYMBOL(pthread_cond_wait, pthread_cond_wait_fake)
DYN_SYMBOL(pthread_create, pthread_create_fake)
DYN_SYMBOL_DEFAULT(pthread_detach)
DYN_SYMBOL_DEFAULT(pthread_exit)
DYN_SYMBOL_DEFAULT(pthread_getschedparam)
DYN_SYMBOL_DEFAULT(pthread_getspecific)
DYN_SYMBOL_DEFAULT(pthread_join)
DYN_SYMBOL_DEFAULT(pthread_key_create)
DYN_SYMBOL_DEFAULT(pthread_key_delete)
DYN_SYMBOL(pthread_mutexattr_destroy, ret0)
DYN_SYMBOL(pthread_mutexattr_init, ret0)
DYN_SYMBOL(pthread_mutexattr_settype, ret0)
DYN_SYMBOL(pthread_mutex_destroy, ret0)
DYN_SYMBOL(pthread_mutex_init, ret0)
DYN_SYMBOL(pthread_mutex_lock, ret0)
DYN_SYMBOL(pthread_mutex_trylock, ret0)
DYN_SYMBOL(pthread_mutex_unlock, ret0)
DYN_SYMBOL(pthread_once, ret0)
DYN_SYMBOL_DEFAULT(pthread_self)
DYN_SYMBOL_DEFAULT(pthread_setschedparam)
DYN_SYMBOL_DEFAULT(pthread_setspecific)
DYN_SYMBOL_DEFAULT(putc)
DYN_SYMBOL_DEFAULT(putchar)
DYN_SYMBOL_DEFAULT(puts)
DYN_SYMBOL_DEFAULT(putwc)
DYN_SYMBOL_DEFAULT(qsort)
DYN_SYMBOL(raise, raise )
DYN_SYMBOL(rand, rand )
DYN_SYMBOL(read, read )
DYN_SYMBOL(readdir, readdir )
DYN_SYMBOL_DEFAULT(realloc)
DYN_SYMBOL_DEFAULT(recvfrom)
DYN_SYMBOL_DEFAULT(remove)
DYN_SYMBOL_DEFAULT(rename)
DYN_SYMBOL_DEFAULT(sched_get_priority_max)
DYN_SYMBOL_DEFAULT(sched_get_priority_min)
DYN_SYMBOL_DEFAULT(sched_yield)
DYN_SYMBOL_DEFAULT(select)
DYN_SYMBOL(sem_destroy, sem_destroy_fake)
DYN_SYMBOL(sem_init, sem_init_fake)
DYN_SYMBOL(sem_post, sem_post_fake)
DYN_SYMBOL(sem_timedwait, sem_timedwait_fake)
DYN_SYMBOL(sem_wait, sem_wait_fake)
DYN_SYMBOL_DEFAULT(sendto)
DYN_SYMBOL_DEFAULT(setjmp)
DYN_SYMBOL_DEFAULT(setlocale)
DYN_SYMBOL_DEFAULT(setsockopt)
DYN_SYMBOL_DEFAULT(setvbuf)
DYN_SYMBOL_DEFAULT(signal)
DYN_SYMBOL_DEFAULT(sin)
DYN_SYMBOL_DEFAULT(sinf)
DYN_SYMBOL_DEFAULT(sinh)
DYN_SYMBOL_DEFAULT(slCreateEngine)
//      todo port opensles
//        SL_IID_ANDROIDCONFIGURATION
//        SL_IID_BUFFERQUEUE
//        SL_IID_ENGINE
//        SL_IID_PLAY
DYN_SYMBOL_DEFAULT(snprintf)
DYN_SYMBOL_DEFAULT(socket)
DYN_SYMBOL_DEFAULT(sprintf)
DYN_SYMBOL_DEFAULT(sqrt)
DYN_SYMBOL_DEFAULT(sqrtf)
DYN_SYMBOL_DEFAULT(srand)
DYN_SYMBOL_DEFAULT(srand48)
DYN_SYMBOL_DEFAULT(sscanf)
DYN_SYMBOL(stat, stat_hook)
DYN_SYMBOL_DEFAULT(stpcpy)
DYN_SYMBOL_DEFAULT(strcat)
DYN_SYMBOL_DEFAULT(strchr)
DYN_SYMBOL(strcmp, sceClibStrcmp)
DYN_SYMBOL_DEFAULT(strcoll)
DYN_SYMBOL_DEFAULT(strcpy)
DYN_SYMBOL_DEFAULT(strcspn)
DYN_SYMBOL_DEFAULT(strerror)
DYN_SYMBOL_DEFAULT(strftime)
DYN_SYMBOL_DEFAULT(strlen)
DYN_SYMBOL(strncat, sceClibStrncat)
DYN_SYMBOL(strncmp, sceClibStrncmp)
DYN_SYMBOL(strncpy, sceClibStrncpy)
DYN_SYMBOL_DEFAULT(strpbrk)
DYN_SYMBOL(strrchr, sceClibStrrchr)
DYN_SYMBOL(strstr, sceClibStrstr)
DYN_SYMBOL_DEFAULT(strtod)
DYN_SYMBOL_DEFAULT(strtoul)
DYN_SYMBOL_DEFAULT(strxfrm)
DYN_SYMBOL_DEFAULT(syscall)
DYN_SYMBOL_DEFAULT(sysconf)
DYN_SYMBOL_DEFAULT(system)
DYN_SYMBOL_DEFAULT(tan)
DYN_SYMBOL_DEFAULT(tanf)
DYN_SYMBOL_DEFAULT(tanh)
DYN_SYMBOL_DEFAULT(time)
DYN_SYMBOL_DEFAULT(tmpfile)
DYN_SYMBOL_DEFAULT(tmpnam)
DYN_SYMBOL_DEFAULT(tolower)
DYN_SYMBOL_DEFAULT(toupper)
DYN_SYMBOL_DEFAULT(towlower)
DYN_SYMBOL_DEFAULT(towupper)
DYN_SYMBOL_DEFAULT(ungetc)
DYN_SYMBOL_DEFAULT(ungetwc)
DYN_SYMBOL_DEFAULT(usleep)
DYN_SYMBOL_DEFAULT(vsnprintf)
DYN_SYMBOL_DEFAULT(vsprintf)
DYN_SYMBOL_DEFAULT(wcrtomb)
DYN_SYMBOL_DEFAULT(wcscoll)
DYN_SYMBOL_DEFAULT(wcscpy)
DYN_SYMBOL_DEFAULT(wcsftime)
DYN_SYMBOL_DEFAULT(wcslen)
DYN_SYMBOL_DEFAULT(wcstombs)
DYN_SYMBOL_DEFAULT(wcsxfrm)
DYN_SYMBOL_DEFAULT(wctob)
DYN_SYMBOL_DEFAULT(wctype)
DYN_SYMBOL_DEFAULT(wmemchr)
DYN_SYMBOL_DEFAULT(wmemcmp)
DYN_SYMBOL_DEFAULT(wmemcpy)
DYN_SYMBOL_DEFAULT(wmemmove)
DYN_SYMBOL_DEFAULT(wmemset)
DYN_SYMBOL_DEFAULT(write)
DYN_SYMBOL_DEFAULT(writev)
